[Settings]
ID = "f3009844-e696-401d-8b6e-5e8e175c8786"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "team/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "team/build/"
  # This will be your default build command
  command = "yarn build"
